### ISSUE TITLE
Missing libinjection?

### ISSUE THREAD

**Issue by LTIOfficial** [iuscommunity-pkg/httpd24u-mod_security2#2]
Hi Folks,
I've installed httpd24u-mod_security2.x86_64 (2.9.1-1.ius.centos7) and am now attempting to install the latest OWASP 3.x CRS files.  Their INSTALL file includes the [following section][0] which strongly suggests that both libinjection and libXML2 are needed.  libXML2 is included with a minimal install of C7, but they mention that libinjection is included with mod-security versions 2.8 and above.  However, it does not appear to be included in your mod_sec 2.9.1.  Am I missing something here?

```
Prerequisites
-------------

    CRS is designed to be used with ModSecurity (although many other
    projects also use the provided rules). CRS version 3.x is designed for
    ModSecurity 2.8 or above. CRS version 3.x makes use of libinjection
    and libXML2. Failure to provide these prerequisites may result in
    serious false negatives and CRS version 3.x should NOT be run without
    these. Note, however, that libinjection is bundled with ModSecurity
    since version 2.8. Additionally, if you are downloading from the
    GitHub repo you will need to install 'git' on your system.
```

Edit by b-harper on 2071-06-01 to include link to Prerequisites section of INSTALL file.

[0]: https://github.com/SpiderLabs/owasp-modsecurity-crs/blob/v3.0.0/INSTALL#L50-L59

**Comment by b-harper** [comment]
Hello @LTIOfficial,

Thanks for taking the time to submit this issue.  Looking over the build log, it would appear that libinjection is compiled into the module via an [embedded library][0].   Are you getting some form of error message that libinjection functionality is not working correctly?


[0]: https://github.com/SpiderLabs/ModSecurity/tree/v2.9.1/apache2/libinjection

**Comment by LTIOfficial** [comment]
No, I actually had not gotten far enough with the install when I read the CRS requirement.  Instead, I simply ran a search on the server for it and, when it was not found, came here to report it as a seemingly missing supplementary 'file', not even considering that it might be more of a function built into mod_sec2 itself.
Self-inflicted premature assumption mystery solved!    ;)

Thanks for helping me understand this clearer, sir!
And thanks for all that you guys do for the rest of us!

**Comment by b-harper** [comment]
Hey @LTIOfficial,

You are welcome and you did not miss anything oblivious.  Typically, embedded libraries are avoided and unless building packages on a regular basis it wouldn't be something to check for.
