### ISSUE TITLE
v2.9.3

### ISSUE THREAD

**Issue by nicjansma** [iuscommunity-pkg/httpd24u-mod_security2#4]
Could we get this updated to https://github.com/SpiderLabs/ModSecurity/releases/tag/v2.9.3?

I'm happy to do the work (e.g. follow [this](https://github.com/iuscommunity-pkg/httpd24u-mod_security2/commit/67a6b71654e8e296e285cb0857a92eccad7028a4)), but I'm entirely ignorant for how the update/release process for this works!

**Comment by carlwgeorge** [comment]
Thanks for raising this issue.  The source repo for this package was lagging behind from when we moved to our new @iusrepo organization.  I've transferred it now, converted it to our new CI system, and update it to version 2.9.3.  The new version will be available in the testing repo soon.
